services:
  openvpn:
    build: .
    container_name: openvpn
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    ports:
      - "1194:1194/udp"
    volumes:
      - ./openvpn-data:/etc/openvpn
      - ./openvpn-data/home:/root/openvpn
    restart: unless-stopped
