FROM ubuntu:22.04

LABEL maintainer="domster704"

RUN apt-get update && apt-get install -y \
    easy-rsa sudo \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /etc/openvpn

EXPOSE 1194/udp

ENTRYPOINT ["sleep", "infinity"]