services:
  openvpn:
    build: .
    container_name: openvpn
    network_mode: host
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    ports:
      - "1194:1194/udp"
    volumes:
      - ./openvpn-data/server:/etc/openvpn/server
      - ./openvpn-data/home:/root/openvpn/
      - ./scripts:/root/openvpn/scripts
    restart: unless-stopped

  agent:
    build:
      context: .
      dockerfile: Dockerfile.agent
    container_name: openvpn-agent
    network_mode: host
    volumes:
      - ./openvpn-data/server:/etc/openvpn/server
      - ./openvpn-data/home:/root/openvpn/
      - ./scripts:/root/openvpn/scripts
    depends_on:
      - openvpn