services:
  openvpn:
    build: .
    container_name: openvpn
    env_file:
      - .env
    cap_add:
      - NET_ADMIN
    volumes:
      - ./openvpn-data/server:/etc/openvpn/server
      - ./openvpn-data/home:/root/openvpn/
      - ./scripts:/root/openvpn/scripts
    restart: unless-stopped
    ports:
      - "1194:1194/udp"
      - ${MGMT_PORT}:${MGMT_PORT}

