services:
  openvpn:
    build: .
    container_name: openvpn
    network_mode: host
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    ports:
      - "1194:1194/udp"
    volumes:
      - ./openvpn-data/server:/etc/openvpn/server
      - ./openvpn-data/home:/root/openvpn/
    restart: unless-stopped
